services:
  - type: web
    name: trustchain-backend
    runtime: python
    region: oregon
    plan: free
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    healthCheckPath: /health
    autoDeploy: true
    envVars:
      - key: DATABASE_URL
        value: postgresql+asyncpg://trustchain:npg_UzgBm5Xo0sJa@ep-damp-paper-b301iffa.c-4.ap-southeast-1.aws.neon.tech/trustchain_db?ssl=require
      - key: DATABASE_URL_SYNC
        value: postgresql://trustchain:npg_UzgBm5Xo0sJa@ep-damp-paper-b301iffa.c-4.ap-southeast-1.aws.neon.tech/trustchain_db?sslmode=require
      - key: REDIS_URL
        value: ""
      - key: JWT_SECRET
        value: super_secret_jwt_key_trustchain_production_grade_security_token_2026_xyz
      - key: JWT_ALGORITHM
        value: HS256
      - key: ACCESS_TOKEN_EXPIRE_MINUTES
        value: "60"
      - key: REFRESH_TOKEN_EXPIRE_DAYS
        value: "7"
      - key: ENVIRONMENT
        value: production
      - key: DEBUG
        value: "false"
      - key: CORS_ORIGINS
        value: "https://frontend-peach-one-11.vercel.app,https://frontend-myvr78xoy-sshhaaddooww301s-projects.vercel.app,http://localhost:3000"
      - key: BLOCKCHAIN_RPC_URL
        value: "http://localhost:8545"
      - key: BLOCKCHAIN_PRIVATE_KEY
        value: "0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80"
      - key: BLOCKCHAIN_CHAIN_ID
        value: "31337"
      - key: IOT_SIGNING_KEY
        value: "trustchain_iot_master_signing_key_production_2026"
      - key: PINATA_API_KEY
        value: ""
      - key: PINATA_API_SECRET
        value: ""
      - key: PINATA_JWT
        value: ""
      - key: IPFS_GATEWAY_URL
        value: "https://gateway.pinata.cloud/ipfs/"
