from enum import Enum


class UserRole(str, Enum):
    SUPER_ADMIN = "SUPER_ADMIN"
    MANUFACTURER = "MANUFACTURER"
    DISTRIBUTOR = "DISTRIBUTOR"
    WAREHOUSE = "WAREHOUSE"
    LOGISTICS = "LOGISTICS"
    RETAILER = "RETAILER"
    AUDITOR = "AUDITOR"


class OrganizationType(str, Enum):
    MANUFACTURER = "MANUFACTURER"
    DISTRIBUTOR = "DISTRIBUTOR"
    WAREHOUSE = "WAREHOUSE"
    LOGISTICS = "LOGISTICS"
    RETAILER = "RETAILER"


class ProductCategory(str, Enum):
    PHARMACEUTICAL = "PHARMACEUTICAL"
    FOOD = "FOOD"
    BEVERAGE = "BEVERAGE"
    MEDICAL_DEVICE = "MEDICAL_DEVICE"
    SUPPLEMENT = "SUPPLEMENT"
    COSMETIC = "COSMETIC"
    OTHER = "OTHER"


class ProductStatus(str, Enum):
    ACTIVE = "ACTIVE"
    ARCHIVED = "ARCHIVED"
    DISCONTINUED = "DISCONTINUED"


class BatchStatus(str, Enum):
    CREATED = "CREATED"
    REGISTERED = "REGISTERED"
    IN_TRANSIT = "IN_TRANSIT"
    WAREHOUSE = "WAREHOUSE"
    DISTRIBUTED = "DISTRIBUTED"
    RETAIL = "RETAIL"
    SOLD = "SOLD"
    QUARANTINED = "QUARANTINED"
    RECALLED = "RECALLED"
    EXPIRED = "EXPIRED"
    COUNTERFEIT = "COUNTERFEIT"


class PackageStatus(str, Enum):
    CREATED = "CREATED"
    REGISTERED = "REGISTERED"
    IN_TRANSIT = "IN_TRANSIT"
    WAREHOUSE = "WAREHOUSE"
    RETAIL = "RETAIL"
    SOLD = "SOLD"
    QUARANTINED = "QUARANTINED"
    RECALLED = "RECALLED"
    COUNTERFEIT = "COUNTERFEIT"
    EXPIRED = "EXPIRED"


class ShipmentStatus(str, Enum):
    CREATED = "CREATED"
    PICKED_UP = "PICKED_UP"
    IN_TRANSIT = "IN_TRANSIT"
    ARRIVED = "ARRIVED"
    OUT_FOR_DELIVERY = "OUT_FOR_DELIVERY"
    DELIVERED = "DELIVERED"
    CANCELLED = "CANCELLED"
    QUARANTINED = "QUARANTINED"


class IoTSimulationMode(str, Enum):
    NORMAL = "NORMAL"
    COLD_CHAIN_BREACH = "COLD_CHAIN_BREACH"
    GPS_ANOMALY = "GPS_ANOMALY"
    SENSOR_TAMPERING = "SENSOR_TAMPERING"
    REPLAY_ATTACK = "REPLAY_ATTACK"
    DEVICE_OFFLINE = "DEVICE_OFFLINE"


class FraudAlertType(str, Enum):
    DUPLICATE_PACKAGE = "DUPLICATE_PACKAGE"
    IMPOSSIBLE_MOVEMENT = "IMPOSSIBLE_MOVEMENT"
    COLD_CHAIN_BREACH = "COLD_CHAIN_BREACH"
    INVALID_SIGNATURE = "INVALID_SIGNATURE"
    REPLAY_ATTACK = "REPLAY_ATTACK"
    UNAUTHORIZED_TRANSFER = "UNAUTHORIZED_TRANSFER"
    EXPIRED_PRODUCT = "EXPIRED_PRODUCT"
    DOCUMENT_TAMPERING = "DOCUMENT_TAMPERING"
    GPS_ANOMALY = "GPS_ANOMALY"


class RiskLevel(str, Enum):
    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"
    CRITICAL = "CRITICAL"


class AlertStatus(str, Enum):
    OPEN = "OPEN"
    INVESTIGATING = "INVESTIGATING"
    RESOLVED = "RESOLVED"
    FALSE_POSITIVE = "FALSE_POSITIVE"


class DocumentType(str, Enum):
    MANUFACTURING_CERTIFICATE = "MANUFACTURING_CERTIFICATE"
    LAB_REPORT = "LAB_REPORT"
    REGULATORY_LICENSE = "REGULATORY_LICENSE"
    QUALITY_CERTIFICATE = "QUALITY_CERTIFICATE"
    INVOICE = "INVOICE"
    COMPLIANCE_REPORT = "COMPLIANCE_REPORT"
    OTHER = "OTHER"


class OracleStatus(str, Enum):
    ACTIVE = "ACTIVE"
    INACTIVE = "INACTIVE"
    SUSPENDED = "SUSPENDED"


class BlockchainTxStatus(str, Enum):
    PENDING = "PENDING"
    CONFIRMED = "CONFIRMED"
    FAILED = "FAILED"


class RecallStatus(str, Enum):
    INITIATED = "INITIATED"
    ACTIVE = "ACTIVE"
    COMPLETED = "COMPLETED"
    CANCELLED = "CANCELLED"


class HandoverEventType(str, Enum):
    PICKUP = "PICKUP"
    TRANSFER = "TRANSFER"
    DELIVERY = "DELIVERY"
    WAREHOUSE_IN = "WAREHOUSE_IN"
    WAREHOUSE_OUT = "WAREHOUSE_OUT"
    RETAIL_RECEIVE = "RETAIL_RECEIVE"
    CONSUMER_SALE = "CONSUMER_SALE"
    QUARANTINE = "QUARANTINE"
    RETURN = "RETURN"
